/* EXO1 Q1 */
CREATE OR REPLACE TRIGGER CTRL
BEFORE INSERT UPDATE
ON CONTROLE
BEGIN
    IF NEW.DATEFIN IS NULL THEN
        NEW.DATEFIN = NEW.DATEDEB;
    END IF;

    IF NEW.TYPEC IN {'TESTS', 'TESTSRATTRAPAGE', 'INTERROGATIONS'} THEN
        NEW.DATEFIN = NEW.DATEDEB;
    END IF;

    IF NEW.NOTEMAX IS NULL THEN
        NEW.NOTEMAX = 20;
    END IF; 
END;

/* EXO1 Q2 */
CREATE OR REPLACE TRIGGER NOTE
BEFORE INSERT UPDATE
ON NOTATION
BEGIN
    FOR P IN (SELECT NOTEMAX FROM CONTROLE WHERE NEW.IDC = CONTROLE.IDC)
    LOOP
        NEW.NOTEDEF = NEW.NOTE/P.NOTEMAX*20;
    END LOOP;
END;

/* EXO2 Q1 */
CREATE OR REPLACE TRIGGER EMPRT
BEFORE INSERT
ON EMPRUNT
BEGIN
    FOR P IN (SELECT COUNT(*) TOTAL FROM EMPRUNT WHERE DATERET IS NULLAND NEW.IDA = EMPRUNT.IDA)
    LOOP
        IF P.TOTAL > 5 THEN
            NEW = NULL;
        END IF;
    END LOOP;
END;

/* EXO2 Q2 */
CREATE OR REPLACE TRIGGER NBEMPRT
BEFORE INSERT
ON EMPRUNT
BEGIN
    FOR P IN (SELECT COUNT(*) TOTAL, EMPRUNT FROM EMPRUNT WHERE DATERET IS NULL AND NEW.IDA = EMPRUNT.IDA)
    LOOP
        UPDATE ABONNE SET NBEMPRUNT = P.TOTAL WHERE NEW.IDA = EMPRUNT.IDA;
    END LOOP;
END;