#!/bin/bash

if (($# == 0)); then
  echo "dataglue: argument(s) manquant(s)" >> /dev/stderr
  echo "usage: dataglue datagramme {datagramme}" >> /dev/stderr
  exit 1
fi

tail --lines +11 --silent "$@"
