/* EXO1 */
CREATE OR REPLACE TRIGGER CTRL
BEFORE INSERT UPDATE
ON CONTROLE
BEGIN
    IF NEW.DATEFIN IS NULL THEN
        NEW.DATEFIN = NEW.DATEDEB;
    END IF;

    IF NEW.TYPEC IN {'TESTS', 'TESTSRATTRAPAGE', 'INTERROGATIONS'} THEN
        NEW.DATEFIN = NEW.DATEDEB;
    END IF;

    IF NEW.NOTEMAX IS NULL THEN
        NEW.NOTEMAX = 20;
    END IF; 
END;

/* EXO2 */
CREATE OR REPLACE TRIGGER NOTE
BEFORE INSERT UPDATE
ON NOTATION
BEGIN
    
END;
