/* EXO1 */
CREATE OR REPLACE TRIGGER SUPR_DIS
BEFORE DELETE
ON MODULE
FOR EACH ROW
BEGIN
    FOR P IN (SELECT CODE FROM ENSEIGNT)
    LOOP
        IF P.CODE = :OLD.CODE THEN
            RAISE_APPLICATION_ERROR(-20001, "Module encore enseigne !");
        END IF;
    END LOOP;
END;

/* EXO2 */
CREATE OR REPLACE TRIGGER INS_DIS
BEFORE INSERT
ON MODULE
FOR EACH ROW
BEGIN
    FOR P IN (SELECT CODE FROM ENSEIGNT)
    LOOP
        IF P.CODE = :NEW.CODE THEN
            RAISE_APPLICATION_ERROR(-20001, "Module encore enseigne !");
        END IF;
    END LOOP;
END;

/* EXO3 */
CREATE OR REPLACE TRIGGER NOTE
BEFORE INSERT OR UPDATE
ON NOTATION
FOR EACH ROW
BEGIN
    IF :NEW.MOY_CC IS NULL THEN
        :NEW.MOY_CC = 0;
    END IF;

    IF :NEW.MOY_TEST IS NULL THEN
        :NEW.MOY_TEST = 0;
    END IF;
END;

/* EXO4 */
CREATE OR REPLACE TRIGGER NOTE
BEFORE INSERT OR UPDATE
ON NOTATION
FOR EACH ROW
DECLARE
    NB NUMBER(2,0);
BEGIN
    SELECT COUNT(*) INTO NB FROM ENSEIGNT WHERE CODE = :NEW.CODE AND NUM_ET = :NEW.NUM_ET;
    IF NB = 0 THEN
        RAISE_APPLICATION_ERROR(-20007, "L eleve ne participe pas a ce cours !")
    END IF;
END;

/* EXO5 */
