/* EXO1 */
CREATE OR REPLACE TRIGGER SUPR_DIS
BEFORE DELETE
ON MODULE
FOR EACH ROW
BEGIN
    FOR P IN (SELECT CODE FROM ENSEIGNT)
    LOOP
        IF P.CODE == :OLD.CODE THEN
            RAISE_APPLICATION_ERROR(-20001, "Module encore enseigne !")
        END IF;
    END LOOP;
END;